logging:
  version: 1
  formatters:
    formatter:
      (): coloredlogs.ColoredFormatter
      format: "[%(asctime)s] [%(name)s] [%(levelname)s] [%(threadName)s] [%(thread)d] %(message)s"
  handlers:
    console:
      class: "logging.StreamHandler"
      level: "DEBUG"
      formatter: "formatter"
      stream: "ext://sys.stdout"
  root:
    level: "DEBUG"
    handlers: ["console"]

pip:
  allowed_packages:
    llm: ["0.10.0", "latest"]
    numpy: ["1.24.0", "latest"]
    pandas: ["1.5.0", "latest"]
    requests: ["2.28.0", "latest"]

brew:
  allowed_packages:
    node: ["latest"]
    python: ["latest"]

docker:
  allowed_packages:
    openwebui: ["latest", "0.1.124", "0.1.123"]
    nginx: ["latest", "1.25", "1.24"]
  configurations:
    openwebui:
      image: "ghcr.io/open-webui/open-webui"
      ports:
        "3000": "8080"
      environment:
        OLLAMA_BASE_URL: "https://api.openai.com/v1"
      volumes:
        "open-webui": "/app/backend/data"
      restart: "always"
      access_url: "http://localhost:3000"
    nginx:
      image: "nginx"
      ports:
        "80": "80"
      restart: "always"
      access_url: "http://localhost:80"