logging:
  version: 1
  formatters:
    formatter:
      (): coloredlogs.ColoredFormatter
      format: "[%(asctime)s] [%(name)s] [%(levelname)s] [%(threadName)s] [%(thread)d] %(message)s"
  handlers:
    console:
      class: "logging.StreamHandler"
      level: "DEBUG"
      formatter: "formatter"
      stream: "ext://sys.stdout"
  root:
    level: "DEBUG"
    handlers: ["console"]

pip:
  allowed_packages:
    llm: ["0.10.0", "latest"]
    numpy: ["1.24.0", "latest"]
    pandas: ["1.5.0", "latest"]
    requests: ["2.28.0", "latest"]

brew:
  allowed_packages:
    node: ["latest"]
    python: ["latest"]